# Role 4: BART, T5, and GPT-2 Summarization Benchmark

## 1. Environment and Data Setup

### Loading the df_focused.csv dataset

In [1]:
from google.colab import files

uploaded = files.upload()

Saving df_focused.csv to df_focused.csv

### Loading and Inspecting the data

In [2]:
import pandas as pd

df = pd.read_csv("df_focused.csv")

print("Dataset shape:", df.shape)
print("\nColumns:")
print(df.columns.tolist())

df.head()

Dataset shape: (11814, 14)

Columns:
['uniqueID', 'drugName', 'condition', 'review', 'rating', 'date', 'usefulCount', 'split', 'review_clean', 'review_word_count', 'review_processed', 'vader_score', 'sentiment_label', 'topic_id']

,uniqueID,drugName,condition,review,rating,date,usefulCount,split,review_clean,review_word_count,review_processed,vader_score,sentiment_label,topic_id
0,75612,L-Methylfolate,Depression,"""I have taken anti-depressants for years, with...",10,2017-03-09,54,train,"I have taken anti-depressants for years, with ...",80,taken year improvement mostly moderate severe ...,0.0147,neutral,3
1,96233,Sertraline,Depression,"""1 week on Zoloft for anxiety and mood swings....",8,2011-05-07,3,train,1 week on Zoloft for anxiety and mood swings. ...,51,week zoloft anxiety mood swing take morning br...,0.5423,positive,2
2,121333,Venlafaxine,Depression,"""my gp started me on Venlafaxine yesterday to ...",4,2016-04-27,3,train,my gp started me on Venlafaxine yesterday to h...,136,gp started venlafaxine yesterday help depressi...,-0.5862,negative,4
3,131704,Effexor Xr,Anxiety,"""Was on this med for 5 years. Worked fine but ...",6,2016-12-27,23,train,Was on this med for 5 years. Worked fine but n...,62,med year worked fine not great stopped panic a...,-0.9621,negative,7
4,131909,Effexor Xr,Depression,"""This medicine saved my life. I was at my wits...",10,2013-06-20,166,train,This medicine saved my life. I was at my wits ...,106,medicine saved life wit end ready give doctor ...,0.8112,positive,2

### Verifying all the columns needed

In [3]:
required_columns = [
    "review_clean",
    "rating",
    "vader_score",
    "sentiment_label",
    "topic_id"
]

for column in required_columns:
    print(f"{column}: {column in df.columns}")

review_clean: True
rating: True
vader_score: True
sentiment_label: True
topic_id: True

In [4]:
!pip install -q transformers sentencepiece accelerate rouge-score

  Preparing metadata (setup.py) ... done
  Building wheel for rouge-score (setup.py) ... done

### Changing Runtype to GPU and checking if it runs

In [5]:
import torch

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

print("Device:", device)

if torch.cuda.is_available():
    print("GPU:", torch.cuda.get_device_name(0))
else:
    print("No GPU detected. Check the Colab runtime settings.")

Device: cuda
GPU: Tesla T4

### Creating the fixed 50-review benchmark sample

In [6]:
import pandas as pd

benchmark_candidates = df.copy()

benchmark_candidates["rating"] = pd.to_numeric(
    benchmark_candidates["rating"],
    errors="coerce"
)

# Removing missing and blank reviews
benchmark_candidates = benchmark_candidates.dropna(
    subset=["review_clean"]
).copy()

benchmark_candidates["review_clean"] = (
    benchmark_candidates["review_clean"]
    .astype(str)
    .str.strip()
)

benchmark_candidates = benchmark_candidates[
    benchmark_candidates["review_clean"] != ""
].copy()

# Removing duplicate reviews
benchmark_candidates = benchmark_candidates.drop_duplicates(
    subset=["review_clean"]
).copy()

# low rating OR negative VADER sentiment
benchmark_candidates = benchmark_candidates[
    (benchmark_candidates["rating"] <= 4) |
    (
        benchmark_candidates["sentiment_label"]
        .astype(str)
        .str.lower()
        .eq("negative")
    )
].copy()

# Calculating review length
benchmark_candidates["review_word_count"] = (
    benchmark_candidates["review_clean"]
    .str.split()
    .str.len()
)

# Getting rid of reviews that are too short to summarize meaningfully
benchmark_candidates = benchmark_candidates[
    benchmark_candidates["review_word_count"] >= 20
].copy()

# Ensure enough reviews are available
if len(benchmark_candidates) < 50:
    raise ValueError(
        f"Only {len(benchmark_candidates)} eligible reviews were found. "
        "At least 50 reviews are required."
    )

# Including 25 Depression and 25 Anxiety reviews
if "condition" in benchmark_candidates.columns:
    depression_reviews = benchmark_candidates[
        benchmark_candidates["condition"]
        .astype(str)
        .str.lower()
        .eq("depression")
    ]

    anxiety_reviews = benchmark_candidates[
        benchmark_candidates["condition"]
        .astype(str)
        .str.lower()
        .eq("anxiety")
    ]

    if len(depression_reviews) >= 25 and len(anxiety_reviews) >= 25:
        benchmark_df = pd.concat(
            [
                depression_reviews.sample(n=25, random_state=42),
                anxiety_reviews.sample(n=25, random_state=42)
            ],
            ignore_index=True
        )

        # Shuffling the combined sample
        benchmark_df = benchmark_df.sample(
            frac=1,
            random_state=42
        ).reset_index(drop=True)

    else:
        benchmark_df = benchmark_candidates.sample(
            n=50,
            random_state=42
        ).reset_index(drop=True)

else:
    benchmark_df = benchmark_candidates.sample(
        n=50,
        random_state=42
    ).reset_index(drop=True)

# Adding a unique benchmark ID
benchmark_df.insert(
    0,
    "benchmark_id",
    range(1, 51)
)

# Saving results
benchmark_df.to_csv(
    "benchmark_sample_50.csv",
    index=False
)

print("Eligible candidate reviews:", len(benchmark_candidates))
print("Final benchmark shape:", benchmark_df.shape)

print("\nRating distribution:")
print(benchmark_df["rating"].value_counts().sort_index())

print("\nSentiment distribution:")
print(benchmark_df["sentiment_label"].value_counts(dropna=False))

if "condition" in benchmark_df.columns:
    print("\nCondition distribution:")
    print(benchmark_df["condition"].value_counts(dropna=False))

display(
    benchmark_df[
        [
            "benchmark_id",
            "condition",
            "rating",
            "sentiment_label",
            "review_clean"
        ]
    ].head()
)

Eligible candidate reviews: 6598
Final benchmark shape: (50, 15)

Rating distribution:
rating
1     10
2      2
3      4
4      2
5      1
6      1
7      1
8      8
9      6
10    15
Name: count, dtype: int64

Sentiment distribution:
sentiment_label
negative    47
positive     3
Name: count, dtype: int64

Condition distribution:
condition
Depression    25
Anxiety       25
Name: count, dtype: int64

,benchmark_id,condition,rating,sentiment_label,review_clean
0,1,Depression,2,negative,Really bad. I didn't feel better at all just c...
1,2,Anxiety,10,negative,I have have drug related issues for ~15 years....
2,3,Anxiety,10,negative,This medicine saved my life when I was 17 year...
3,4,Anxiety,10,negative,I am 47 with such an exhausting history of anx...
4,5,Depression,9,negative,"Since 2007, I've taken Lexapro in varying dose..."

### Downloading Fixed Sample

In [7]:
from google.colab import files

files.download("benchmark_sample_50.csv")

## 2. BART Summarization Benchmark

### Loading BART Summarization Model and Test One Review

In [8]:
import torch
from transformers import AutoTokenizer, AutoModelForSeq2SeqLM

BART_MODEL_NAME = "facebook/bart-large-cnn"

print("Loading BART tokenizer...")
bart_tokenizer = AutoTokenizer.from_pretrained(BART_MODEL_NAME)

print("Loading BART model...")
bart_model = AutoModelForSeq2SeqLM.from_pretrained(
    BART_MODEL_NAME,
    torch_dtype=torch.float16 if torch.cuda.is_available() else torch.float32
)

bart_model = bart_model.to(device)
bart_model.eval()

print("BART loaded successfully.")
print("Device:", next(bart_model.parameters()).device)

Loading BART tokenizer...

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

config.json:   0%|          | 0.00/1.58k [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/899k [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.36M [00:00<?, ?B/s]

Loading BART model...

[transformers] `torch_dtype` is deprecated! Use `dtype` instead!

model.safetensors: reconstructing file:   0%|          |  0.00B / 1.63GB

model.safetensors: downloading bytes:           |  0.00B

[transformers] Please make sure the generation config includes `forced_bos_token_id=0`.

Loading weights:   0%|          | 0/511 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/363 [00:00<?, ?B/s]

BART loaded successfully.
Device: cuda:0

### Testing BART on only first benchmark review

In [9]:
test_review = benchmark_df.loc[0, "review_clean"]

inputs = bart_tokenizer(
    test_review,
    return_tensors="pt",
    max_length=1024,
    truncation=True
)

inputs = {
    key: value.to(device)
    for key, value in inputs.items()
}

with torch.no_grad():
    summary_ids = bart_model.generate(
        **inputs,
        max_new_tokens=80,
        min_new_tokens=10,
        num_beams=4,
        no_repeat_ngram_size=3,
        early_stopping=True
    )

bart_test_summary = bart_tokenizer.decode(
    summary_ids[0],
    skip_special_tokens=True
)

print("ORIGINAL REVIEW:\n")
print(test_review)

print("\n" + "=" * 80)

print("\nBART SUMMARY:\n")
print(bart_test_summary)

[transformers] Both `max_new_tokens` (=80) and `max_length`(=142) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `min_new_tokens` (=10) and `min_length`(=56) seem to have been set. `min_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

ORIGINAL REVIEW:

Really bad. I didn't feel better at all just constantly "wired" like I had drank 6 cups of coffee. I couldn't sleep at all.

================================================================================

BART SUMMARY:

Really bad. I didn't feel better at all just constantly "wired" like I had drank 6 cups of coffee. I couldn't sleep at all.

### Testing BART on a longer benchmark review

BART may behave extractively and repeat short patient reviews rather than produce a shorter adverse-event summary. The max_new_tokens and min_new_tokens messages are warnings, not failures. So next I will test BART on a longer review and avoid those warnings.

In [10]:
# Calculating review length in case the column is not already present
benchmark_df["review_word_count"] = (
    benchmark_df["review_clean"]
    .astype(str)
    .str.split()
    .str.len()
)

# Finding reviews with at least 60 words
long_reviews = benchmark_df[
    benchmark_df["review_word_count"] >= 60
].copy()

# Using first longer review available
if len(long_reviews) > 0:
    test_row = long_reviews.iloc[0]
else:
    # Fall back to the longest review in the sample
    test_row = benchmark_df.sort_values(
        "review_word_count",
        ascending=False
    ).iloc[0]

test_review = test_row["review_clean"]

# Tokenization
inputs = bart_tokenizer(
    test_review,
    return_tensors="pt",
    max_length=1024,
    truncation=True
)

inputs = {
    key: value.to(device)
    for key, value in inputs.items()
}

# Generating summary
with torch.no_grad():
    summary_ids = bart_model.generate(
        **inputs,
        max_length=80,
        min_length=10,
        num_beams=4,
        no_repeat_ngram_size=3,
        length_penalty=1.0,
        early_stopping=True
    )

bart_test_summary = bart_tokenizer.decode(
    summary_ids[0],
    skip_special_tokens=True
)

print("BENCHMARK ID:", test_row["benchmark_id"])
print("CONDITION:", test_row["condition"])
print("RATING:", test_row["rating"])
print("WORD COUNT:", test_row["review_word_count"])

print("\nORIGINAL REVIEW:\n")
print(test_review)

print("\n" + "=" * 80)

print("\nBART SUMMARY:\n")
print(bart_test_summary)

BENCHMARK ID: 2
CONDITION: Anxiety
RATING: 10
WORD COUNT: 90

ORIGINAL REVIEW:

I have have drug related issues for ~15 years. Dope, Speed. My, "Psychiatrist" diagnosed me with the word "schizophrenia", Anti-Phychotics are, VERY DANGEROUS!, they increased my anxiety and stress, MANY MANY, times over. Finally, after 15 years, 3 months, no drugs, I have found Oxazepam. 5mg. I read, you can take up too 120mg!. atm, I think I need about 10mg a day. I am doubting, whether I have "schizophrenia", at all. I am down to 1/2 minimum dose, tablet of, DANGEROUS Latuda. So called "treatment", with Anti-Phychotics, is CRIMINAL.

================================================================================

BART SUMMARY:

After 15 years, 3 months, no drugs, I have found Oxazepam 5mg. I am down to 1/2 minimum dose, tablet of, DANGEROUS Latuda. So called "treatment", with Anti-Phychotics, is CRIMINAL.

### Displaying the complete review and summary without horizontal cutoff

In [11]:
import textwrap

print("ORIGINAL REVIEW:\n")
print(textwrap.fill(test_review, width=100))

print("\n" + "=" * 100)

print("\nCURRENT BART SUMMARY:\n")
print(textwrap.fill(bart_test_summary, width=100))

ORIGINAL REVIEW:

I have have drug related issues for ~15 years. Dope, Speed. My, "Psychiatrist" diagnosed me with the
word "schizophrenia", Anti-Phychotics are, VERY DANGEROUS!, they increased my anxiety and stress,
MANY MANY, times over. Finally, after 15 years, 3 months, no drugs, I have found Oxazepam. 5mg. I
read, you can take up too 120mg!. atm, I think I need about 10mg a day. I am doubting, whether I
have "schizophrenia", at all. I am down to 1/2 minimum dose, tablet of, DANGEROUS Latuda. So called
"treatment", with Anti-Phychotics, is CRIMINAL.

====================================================================================================

CURRENT BART SUMMARY:

After 15 years, 3 months, no drugs, I have found Oxazepam 5mg. I am down to 1/2 minimum dose, tablet
of, DANGEROUS Latuda. So called "treatment", with Anti-Phychotics, is CRIMINAL.

### Testing a conservative adverse-event prompt

In [13]:
conservative_prompt = f"""
Summarize only the patient-reported adverse effects and treatment benefits in the review below.
Use neutral language.
Include only information explicitly stated by the patient.
Do not provide medical advice, diagnoses, causal conclusions, or judgmental statements.

Patient review:
{test_review}
""".strip()

inputs = bart_tokenizer(
    conservative_prompt,
    return_tensors="pt",
    max_length=1024,
    truncation=True
)

inputs = {
    key: value.to(device)
    for key, value in inputs.items()
}

with torch.no_grad():
    summary_ids = bart_model.generate(
        **inputs,
        max_length=70,
        min_length=10,
        num_beams=4,
        no_repeat_ngram_size=3,
        length_penalty=1.0,
        early_stopping=True
    )

conservative_bart_summary = bart_tokenizer.decode(
    summary_ids[0],
    skip_special_tokens=True
)

print("ORIGINAL REVIEW:\n")
print(textwrap.fill(test_review, width=100))

print("\n" + "=" * 100)

print("\nSTANDARD BART SUMMARY:\n")
print(textwrap.fill(bart_test_summary, width=100))

print("\n" + "=" * 100)

print("\nCONSERVATIVE-PROMPT BART SUMMARY:\n")
print(textwrap.fill(conservative_bart_summary, width=100))

ORIGINAL REVIEW:

I have have drug related issues for ~15 years. Dope, Speed. My, "Psychiatrist" diagnosed me with the
word "schizophrenia", Anti-Phychotics are, VERY DANGEROUS!, they increased my anxiety and stress,
MANY MANY, times over. Finally, after 15 years, 3 months, no drugs, I have found Oxazepam. 5mg. I
read, you can take up too 120mg!. atm, I think I need about 10mg a day. I am doubting, whether I
have "schizophrenia", at all. I am down to 1/2 minimum dose, tablet of, DANGEROUS Latuda. So called
"treatment", with Anti-Phychotics, is CRIMINAL.

====================================================================================================

STANDARD BART SUMMARY:

After 15 years, 3 months, no drugs, I have found Oxazepam 5mg. I am down to 1/2 minimum dose, tablet
of, DANGEROUS Latuda. So called "treatment", with Anti-Phychotics, is CRIMINAL.

====================================================================================================

CONSERVATIVE-PROMPT BART SUMMARY:

Use neutral language. Summarize only the patient-reported adverse effects and treatment benefits. Do
not provide medical advice, diagnoses, causal conclusions, or judgmental statements.

### Running standard BART on all 50 Benchmark Reviews

In [14]:
import time
import torch
import pandas as pd
from tqdm.auto import tqdm

bart_summaries = []
bart_inference_times = []

# Make sure the model is in evaluation mode
bart_model.eval()

for review in tqdm(
    benchmark_df["review_clean"],
    desc="Generating BART summaries"
):
    review = str(review)

    # Tokenize one review
    inputs = bart_tokenizer(
        review,
        return_tensors="pt",
        max_length=1024,
        truncation=True
    )

    inputs = {
        key: value.to(device)
        for key, value in inputs.items()
    }

    # Synchronize GPU before timing
    if torch.cuda.is_available():
        torch.cuda.synchronize()

    start_time = time.perf_counter()

    # Generate the summary
    with torch.no_grad():
        summary_ids = bart_model.generate(
            **inputs,
            max_length=64,
            min_length=5,
            num_beams=4,
            no_repeat_ngram_size=3,
            length_penalty=1.0,
            early_stopping=True
        )

    # Synchronize again so timing includes completed GPU work
    if torch.cuda.is_available():
        torch.cuda.synchronize()

    elapsed_time = time.perf_counter() - start_time

    summary = bart_tokenizer.decode(
        summary_ids[0],
        skip_special_tokens=True
    )

    bart_summaries.append(summary)
    bart_inference_times.append(elapsed_time)

# Create the BART results dataframe
bart_results_df = benchmark_df.copy()

bart_results_df["bart_summary"] = bart_summaries
bart_results_df["bart_inference_seconds"] = bart_inference_times

# Calculate review and summary lengths
bart_results_df["source_word_count"] = (
    bart_results_df["review_clean"]
    .astype(str)
    .str.split()
    .str.len()
)

bart_results_df["bart_summary_word_count"] = (
    bart_results_df["bart_summary"]
    .astype(str)
    .str.split()
    .str.len()
)

# Summary length divided by original length
bart_results_df["bart_compression_ratio"] = (
    bart_results_df["bart_summary_word_count"]
    / bart_results_df["source_word_count"]
)

# Save results
bart_results_df.to_csv(
    "bart_results_50.csv",
    index=False
)

# Display timing statistics
total_time = sum(bart_inference_times)
average_time = total_time / len(bart_inference_times)

print("\nBART BENCHMARK COMPLETE")
print("=" * 60)
print(f"Reviews processed: {len(bart_results_df)}")
print(f"Total inference time: {total_time:.2f} seconds")
print(f"Average time per review: {average_time:.3f} seconds")
print(
    "Average compression ratio:",
    round(bart_results_df["bart_compression_ratio"].mean(), 3)
)

display(
    bart_results_df[
        [
            "benchmark_id",
            "condition",
            "rating",
            "review_clean",
            "bart_summary",
            "bart_inference_seconds",
            "bart_compression_ratio"
        ]
    ].head(10)
)

Generating BART summaries:   0%|          | 0/50 [00:00<?, ?it/s]

BART BENCHMARK COMPLETE
============================================================
Reviews processed: 50
Total inference time: 43.50 seconds
Average time per review: 0.870 seconds
Average compression ratio: 0.556

,benchmark_id,condition,rating,review_clean,bart_summary,bart_inference_seconds,bart_compression_ratio
0,1,Depression,2,Really bad. I didn't feel better at all just c...,Really bad. I didn't feel better at all just c...,1.170716,1.000000
1,2,Anxiety,10,I have have drug related issues for ~15 years....,"After 15 years, 3 months, no drugs, I have fou...",1.343308,0.333333
2,3,Anxiety,10,This medicine saved my life when I was 17 year...,This medicine saved my life when I was 17 year...,1.401132,0.393939
3,4,Anxiety,10,I am 47 with such an exhausting history of anx...,I am 47 with such an exhausting history of anx...,1.350435,0.611765
4,5,Depression,9,"Since 2007, I've taken Lexapro in varying dose...","Since 2007, I've taken Lexapro in varying dose...",1.375249,0.356061
5,6,Anxiety,1,I have used Xanax for the past 15 years for se...,I have used Xanax for the past 15 years for se...,0.731584,1.000000
6,7,Anxiety,10,Xanax has been a life saver. I have always had...,Xanax has been a life saver. I have always had...,0.951538,0.382812
7,8,Anxiety,4,Been on and off anti depressants for 10 years ...,Been on and off anti depressants for 10 years ...,0.854586,0.287234
8,9,Anxiety,1,I tried it for anxiety and aggresive behavior....,I tried it for anxiety and aggresive behavior....,0.890377,0.775510
9,10,Depression,4,I have been on Cymbalta for depression for 3 w...,I have been on Cymbalta for depression for 3 w...,1.283393,0.470000

In [15]:
from google.colab import files

files.download("bart_results_50.csv")

## 3. T5 Summarization Benchmark

### T5 Benchmark Test and removing bart from GPU memory

In [16]:
import gc
import torch

del bart_model
del bart_tokenizer

gc.collect()

if torch.cuda.is_available():
    torch.cuda.empty_cache()

print("BART removed from GPU memory.")
print(
    "GPU memory currently allocated:",
    round(torch.cuda.memory_allocated() / 1024**3, 2),
    "GB"
)

BART removed from GPU memory.
GPU memory currently allocated: 0.01 GB

### Loading T5 Summarization Model

In [17]:
from transformers import AutoTokenizer, AutoModelForSeq2SeqLM

T5_MODEL_NAME = "google-t5/t5-small"

print("Loading T5 tokenizer...")
t5_tokenizer = AutoTokenizer.from_pretrained(T5_MODEL_NAME)

print("Loading T5 model...")
t5_model = AutoModelForSeq2SeqLM.from_pretrained(
    T5_MODEL_NAME,
    torch_dtype=(
        torch.float16
        if torch.cuda.is_available()
        else torch.float32
    )
)

t5_model = t5_model.to(device)
t5_model.eval()

print("T5 loaded successfully.")
print("Device:", next(t5_model.parameters()).device)

Loading T5 tokenizer...

config.json:   0%|          | 0.00/1.21k [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/2.32k [00:00<?, ?B/s]

spiece.model:   0%|          | 0.00/792k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.39M [00:00<?, ?B/s]

Loading T5 model...

model.safetensors: reconstructing file:   0%|          |  0.00B /  242MB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/131 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/147 [00:00<?, ?B/s]

T5 loaded successfully.
Device: cuda:0

### Testing T5 on the same long review

In [18]:
import textwrap

# Reuse the longer review selected during the BART test
test_review = str(test_row["review_clean"])

# T5 requires the summarization task prefix
t5_input_text = "summarize: " + test_review

inputs = t5_tokenizer(
    t5_input_text,
    return_tensors="pt",
    max_length=512,
    truncation=True
)

inputs = {
    key: value.to(device)
    for key, value in inputs.items()
}

with torch.no_grad():
    summary_ids = t5_model.generate(
        **inputs,
        max_length=64,
        min_length=5,
        num_beams=4,
        no_repeat_ngram_size=3,
        length_penalty=1.0,
        early_stopping=True
    )

t5_test_summary = t5_tokenizer.decode(
    summary_ids[0],
    skip_special_tokens=True
)

print("BENCHMARK ID:", test_row["benchmark_id"])
print("CONDITION:", test_row["condition"])
print("RATING:", test_row["rating"])

print("\nORIGINAL REVIEW:\n")
print(textwrap.fill(test_review, width=100))

print("\n" + "=" * 100)

print("\nT5 SUMMARY:\n")
print(textwrap.fill(t5_test_summary, width=100))

BENCHMARK ID: 2
CONDITION: Anxiety
RATING: 10

ORIGINAL REVIEW:

I have have drug related issues for ~15 years. Dope, Speed. My, "Psychiatrist" diagnosed me with the
word "schizophrenia", Anti-Phychotics are, VERY DANGEROUS!, they increased my anxiety and stress,
MANY MANY, times over. Finally, after 15 years, 3 months, no drugs, I have found Oxazepam. 5mg. I
read, you can take up too 120mg!. atm, I think I need about 10mg a day. I am doubting, whether I
have "schizophrenia", at all. I am down to 1/2 minimum dose, tablet of, DANGEROUS Latuda. So called
"treatment", with Anti-Phychotics, is CRIMINAL.

====================================================================================================

T5 SUMMARY:

my "Psychiatrist" diagnosed me with the word "schizophrenia" anti-Phychotics are, VERY DANGEROUS!,
they increased my anxiety and stress, times over. after 15 years, 3 months, no drugs, I have found
Oxazep

### Running T5 on all 50 benchmark Reviews

In [19]:
import time
import torch
import pandas as pd
from tqdm.auto import tqdm

t5_summaries = []
t5_inference_times = []

# Make sure the model is in evaluation mode
t5_model.eval()

for review in tqdm(
    benchmark_df["review_clean"],
    desc="Generating T5 summaries"
):
    review = str(review)

    # T5 needs the task prefix
    t5_input_text = "summarize: " + review

    # Tokenize one review
    inputs = t5_tokenizer(
        t5_input_text,
        return_tensors="pt",
        max_length=512,
        truncation=True
    )

    inputs = {
        key: value.to(device)
        for key, value in inputs.items()
    }

    # Synchronize the GPU before timing
    if torch.cuda.is_available():
        torch.cuda.synchronize()

    start_time = time.perf_counter()

    # Generate the summary
    with torch.no_grad():
        summary_ids = t5_model.generate(
            **inputs,
            max_length=64,
            min_length=5,
            num_beams=4,
            no_repeat_ngram_size=3,
            length_penalty=1.0,
            early_stopping=True
        )

    # Synchronize again so timing includes completed GPU work
    if torch.cuda.is_available():
        torch.cuda.synchronize()

    elapsed_time = time.perf_counter() - start_time

    summary = t5_tokenizer.decode(
        summary_ids[0],
        skip_special_tokens=True
    )

    t5_summaries.append(summary)
    t5_inference_times.append(elapsed_time)

# Create the T5 results dataframe
t5_results_df = benchmark_df.copy()

t5_results_df["t5_summary"] = t5_summaries
t5_results_df["t5_inference_seconds"] = t5_inference_times

# Calculate source and summary word counts
t5_results_df["source_word_count"] = (
    t5_results_df["review_clean"]
    .astype(str)
    .str.split()
    .str.len()
)

t5_results_df["t5_summary_word_count"] = (
    t5_results_df["t5_summary"]
    .astype(str)
    .str.split()
    .str.len()
)

# Calculate compression ratio
t5_results_df["t5_compression_ratio"] = (
    t5_results_df["t5_summary_word_count"]
    / t5_results_df["source_word_count"]
)

# Save the results
t5_results_df.to_csv(
    "t5_results_50.csv",
    index=False
)

# Calculate benchmark statistics
total_time = sum(t5_inference_times)
average_time = total_time / len(t5_inference_times)
average_compression = t5_results_df[
    "t5_compression_ratio"
].mean()

print("\nT5 BENCHMARK COMPLETE")
print("=" * 60)
print(f"Reviews processed: {len(t5_results_df)}")
print(f"Total inference time: {total_time:.2f} seconds")
print(f"Average time per review: {average_time:.3f} seconds")
print(
    "Average compression ratio:",
    round(average_compression, 3)
)

display(
    t5_results_df[
        [
            "benchmark_id",
            "condition",
            "rating",
            "review_clean",
            "t5_summary",
            "t5_inference_seconds",
            "t5_compression_ratio"
        ]
    ].head(10)
)

Generating T5 summaries:   0%|          | 0/50 [00:00<?, ?it/s]

T5 BENCHMARK COMPLETE
============================================================
Reviews processed: 50
Total inference time: 37.70 seconds
Average time per review: 0.754 seconds
Average compression ratio: 0.348

,benchmark_id,condition,rating,review_clean,t5_summary,t5_inference_seconds,t5_compression_ratio
0,1,Depression,2,Really bad. I didn't feel better at all just c...,"I didn't feel better at all just constantly ""w...",0.774158,0.708333
1,2,Anxiety,10,I have have drug related issues for ~15 years....,"my ""Psychiatrist"" diagnosed me with the word ""...",3.510269,0.344444
2,3,Anxiety,10,This medicine saved my life when I was 17 year...,this medicine saved my life when I was 17 year...,1.971602,0.318182
3,4,Anxiety,10,I am 47 with such an exhausting history of anx...,47-year-old is alcohol free with no panic atta...,0.628883,0.200000
4,5,Depression,9,"Since 2007, I've taken Lexapro in varying dose...",my body is extremely sensitive to certain type...,1.175253,0.227273
5,6,Anxiety,1,I have used Xanax for the past 15 years for se...,I have used Xanax for the past 15 years for se...,0.906559,1.027027
6,7,Anxiety,10,Xanax has been a life saver. I have always had...,Xanax was diagnosed with a brain tumor at 26. ...,0.603240,0.195312
7,8,Anxiety,4,Been on and off anti depressants for 10 years ...,running helps me more than anything but I fear...,0.586069,0.329787
8,9,Anxiety,1,I tried it for anxiety and aggresive behavior....,in a few minutes of taking the first dose I be...,0.418498,0.387755
9,10,Depression,4,I have been on Cymbalta for depression for 3 w...,I have had a wide range of side effects sleepl...,0.877778,0.460000

In [20]:
from google.colab import files

files.download("t5_results_50.csv")

### Removing T5 from GPU Memory

In [21]:
import gc
import torch

del t5_model
del t5_tokenizer

gc.collect()

if torch.cuda.is_available():
    torch.cuda.empty_cache()

print("T5 removed from GPU memory.")
print(
    "GPU memory currently allocated:",
    round(torch.cuda.memory_allocated() / 1024**3, 2),
    "GB"
)

T5 removed from GPU memory.
GPU memory currently allocated: 0.01 GB

## 4. GPT-2 Text Generation Benchmark

### Loading GPT-2

In [22]:
from transformers import AutoTokenizer, AutoModelForCausalLM

GPT2_MODEL_NAME = "gpt2"

print("Loading GPT-2 tokenizer...")
gpt2_tokenizer = AutoTokenizer.from_pretrained(GPT2_MODEL_NAME)

# GPT-2 does not have a default padding token
gpt2_tokenizer.pad_token = gpt2_tokenizer.eos_token

print("Loading GPT-2 model...")
gpt2_model = AutoModelForCausalLM.from_pretrained(
    GPT2_MODEL_NAME,
    dtype=(
        torch.float16
        if torch.cuda.is_available()
        else torch.float32
    )
)

gpt2_model.config.pad_token_id = gpt2_tokenizer.eos_token_id

gpt2_model = gpt2_model.to(device)
gpt2_model.eval()

print("GPT-2 loaded successfully.")
print("Device:", next(gpt2_model.parameters()).device)

Loading GPT-2 tokenizer...

config.json:   0%|          | 0.00/665 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/26.0 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/1.04M [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.36M [00:00<?, ?B/s]

Loading GPT-2 model...

model.safetensors: reconstructing file:   0%|          |  0.00B /  548MB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/148 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/124 [00:00<?, ?B/s]

GPT-2 loaded successfully.
Device: cuda:0

### Testing GPT-2 on the same long review

In [23]:
import textwrap
import torch

test_review = str(test_row["review_clean"])

gpt2_prompt = (
    "Patient review:\n"
    f"{test_review}\n\n"
    "Concise adverse-event summary:"
)

inputs = gpt2_tokenizer(
    gpt2_prompt,
    return_tensors="pt",
    max_length=900,
    truncation=True
)

inputs = {
    key: value.to(device)
    for key, value in inputs.items()
}

prompt_length = inputs["input_ids"].shape[1]

with torch.no_grad():
    output_ids = gpt2_model.generate(
        **inputs,
        max_new_tokens=64,
        min_new_tokens=5,
        num_beams=4,
        no_repeat_ngram_size=3,
        early_stopping=True,
        pad_token_id=gpt2_tokenizer.eos_token_id,
        eos_token_id=gpt2_tokenizer.eos_token_id
    )

# Decode only the newly generated text, excluding the prompt
generated_ids = output_ids[0][prompt_length:]

gpt2_test_summary = gpt2_tokenizer.decode(
    generated_ids,
    skip_special_tokens=True
).strip()

print("BENCHMARK ID:", test_row["benchmark_id"])
print("CONDITION:", test_row["condition"])
print("RATING:", test_row["rating"])

print("\nORIGINAL REVIEW:\n")
print(textwrap.fill(test_review, width=100))

print("\n" + "=" * 100)

print("\nGPT-2 OUTPUT:\n")
print(textwrap.fill(gpt2_test_summary, width=100))

BENCHMARK ID: 2
CONDITION: Anxiety
RATING: 10

ORIGINAL REVIEW:

I have have drug related issues for ~15 years. Dope, Speed. My, "Psychiatrist" diagnosed me with the
word "schizophrenia", Anti-Phychotics are, VERY DANGEROUS!, they increased my anxiety and stress,
MANY MANY, times over. Finally, after 15 years, 3 months, no drugs, I have found Oxazepam. 5mg. I
read, you can take up too 120mg!. atm, I think I need about 10mg a day. I am doubting, whether I
have "schizophrenia", at all. I am down to 1/2 minimum dose, tablet of, DANGEROUS Latuda. So called
"treatment", with Anti-Phychotics, is CRIMINAL.

====================================================================================================

GPT-2 OUTPUT:

I was diagnosed with Schizophrenia at the age of 15. I was diagnosed as schizophrenic at the time of
my diagnosis. I had been diagnosed with schizophrenia for over 15 years. I have never been diagnosed
as a schizophrenic. I do not know if I am schizophrenic or not, but I am

GPT-2 loaded correctly, but its output shows exactly why it is a weak summarization model for this project.

It introduced unsupported and contradictory details such as:

“diagnosed… at the age of 15”
“diagnosed as schizophrenic”
“I have never been diagnosed”

### Running GPT-2 on all 50 Benchmark Reviews

In [24]:
import time
import torch
import pandas as pd
from tqdm.auto import tqdm

gpt2_outputs = []
gpt2_inference_times = []

# Make sure GPT-2 is in evaluation mode
gpt2_model.eval()

for review in tqdm(
    benchmark_df["review_clean"],
    desc="Generating GPT-2 outputs"
):
    review = str(review)

    # Prompt GPT-2 to produce an adverse-event summary
    gpt2_prompt = (
        "Patient review:\n"
        f"{review}\n\n"
        "Concise adverse-event summary:"
    )

    # Tokenize the prompt
    inputs = gpt2_tokenizer(
        gpt2_prompt,
        return_tensors="pt",
        max_length=900,
        truncation=True
    )

    inputs = {
        key: value.to(device)
        for key, value in inputs.items()
    }

    # Record the prompt length so it can be removed from the output
    prompt_length = inputs["input_ids"].shape[1]

    # Synchronize GPU before timing
    if torch.cuda.is_available():
        torch.cuda.synchronize()

    start_time = time.perf_counter()

    # Generate GPT-2 continuation
    with torch.no_grad():
        output_ids = gpt2_model.generate(
            **inputs,
            max_new_tokens=64,
            min_new_tokens=5,
            num_beams=4,
            no_repeat_ngram_size=3,
            early_stopping=True,
            pad_token_id=gpt2_tokenizer.eos_token_id,
            eos_token_id=gpt2_tokenizer.eos_token_id
        )

    # Synchronize GPU again so timing is accurate
    if torch.cuda.is_available():
        torch.cuda.synchronize()

    elapsed_time = time.perf_counter() - start_time

    # Remove the original prompt and decode only generated text
    generated_ids = output_ids[0][prompt_length:]

    generated_text = gpt2_tokenizer.decode(
        generated_ids,
        skip_special_tokens=True
    ).strip()

    gpt2_outputs.append(generated_text)
    gpt2_inference_times.append(elapsed_time)

# Create results dataframe
gpt2_results_df = benchmark_df.copy()

gpt2_results_df["gpt2_output"] = gpt2_outputs
gpt2_results_df["gpt2_inference_seconds"] = gpt2_inference_times

# Calculate source and output word counts
gpt2_results_df["source_word_count"] = (
    gpt2_results_df["review_clean"]
    .astype(str)
    .str.split()
    .str.len()
)

gpt2_results_df["gpt2_output_word_count"] = (
    gpt2_results_df["gpt2_output"]
    .astype(str)
    .str.split()
    .str.len()
)

# Calculate output-to-source length ratio
gpt2_results_df["gpt2_compression_ratio"] = (
    gpt2_results_df["gpt2_output_word_count"]
    / gpt2_results_df["source_word_count"]
)

# Save GPT-2 results
gpt2_results_df.to_csv(
    "gpt2_results_50.csv",
    index=False
)

# Calculate benchmark statistics
total_time = sum(gpt2_inference_times)
average_time = total_time / len(gpt2_inference_times)
average_compression = (
    gpt2_results_df["gpt2_compression_ratio"].mean()
)

print("\nGPT-2 BENCHMARK COMPLETE")
print("=" * 60)
print(f"Reviews processed: {len(gpt2_results_df)}")
print(f"Total inference time: {total_time:.2f} seconds")
print(f"Average time per review: {average_time:.3f} seconds")
print(
    "Average output-to-source ratio:",
    round(average_compression, 3)
)

display(
    gpt2_results_df[
        [
            "benchmark_id",
            "condition",
            "rating",
            "review_clean",
            "gpt2_output",
            "gpt2_inference_seconds",
            "gpt2_compression_ratio"
        ]
    ].head(10)
)

Generating GPT-2 outputs:   0%|          | 0/50 [00:00<?, ?it/s]

GPT-2 BENCHMARK COMPLETE
============================================================
Reviews processed: 50
Total inference time: 53.17 seconds
Average time per review: 1.063 seconds
Average output-to-source ratio: 0.814

,benchmark_id,condition,rating,review_clean,gpt2_output,gpt2_inference_seconds,gpt2_compression_ratio
0,1,Depression,2,Really bad. I didn't feel better at all just c...,I was diagnosed with a rare form of cancer. I ...,2.219692,2.250000
1,2,Anxiety,10,I have have drug related issues for ~15 years....,I was diagnosed with Schizophrenia at the age ...,3.879561,0.577778
2,3,Anxiety,10,This medicine saved my life when I was 17 year...,This is the most common adverse event that occ...,3.490853,0.401515
3,4,Anxiety,10,I am 47 with such an exhausting history of anx...,I was diagnosed with anxiety in the early 1990...,2.895446,0.611765
4,5,Depression,9,"Since 2007, I've taken Lexapro in varying dose...",I have been taking this for over 2 weeks now. ...,2.242284,0.371212
5,6,Anxiety,1,I have used Xanax for the past 15 years for se...,1. Xanax does not work for me.\n\n2. It does n...,1.115986,1.270270
6,7,Anxiety,10,Xanax has been a life saver. I have always had...,I was diagnosed with a brain tumour at 26 year...,0.800677,0.445312
7,8,Anxiety,4,Been on and off anti depressants for 10 years ...,I've been taking Paxil for about a year now. I...,0.788991,0.521277
8,9,Anxiety,1,I tried it for anxiety and aggresive behavior....,I have been using Buspar for over a year now. ...,0.783017,1.020408
9,10,Depression,4,I have been on Cymbalta for depression for 3 w...,This is a very serious adverse event. I am not...,0.781287,0.580000

## 5. Model Comparison and Exporting Benchmark Deliverabes

### Combing the three model benchmark results (BART, T5, and GPT-2)

In [25]:
import pandas as pd
from difflib import SequenceMatcher

# Start with the shared benchmark information
base_columns = [
    "benchmark_id",
    "condition",
    "rating",
    "review_clean"
]

comparison_df = benchmark_df[base_columns].copy()

# Add BART results
comparison_df = comparison_df.merge(
    bart_results_df[
        [
            "benchmark_id",
            "bart_summary",
            "bart_inference_seconds",
            "bart_compression_ratio"
        ]
    ],
    on="benchmark_id",
    how="left"
)

# Add T5 results
comparison_df = comparison_df.merge(
    t5_results_df[
        [
            "benchmark_id",
            "t5_summary",
            "t5_inference_seconds",
            "t5_compression_ratio"
        ]
    ],
    on="benchmark_id",
    how="left"
)

# Add GPT-2 results
comparison_df = comparison_df.merge(
    gpt2_results_df[
        [
            "benchmark_id",
            "gpt2_output",
            "gpt2_inference_seconds",
            "gpt2_compression_ratio"
        ]
    ],
    on="benchmark_id",
    how="left"
)

# Verify that all 50 reviews are still present
assert len(comparison_df) == 50, (
    f"Expected 50 rows, but found {len(comparison_df)}."
)

# Save all model outputs in one file
comparison_df.to_csv(
    "model_comparison_50.csv",
    index=False
)

print("Combined comparison shape:", comparison_df.shape)

display(
    comparison_df[
        [
            "benchmark_id",
            "condition",
            "rating",
            "review_clean",
            "bart_summary",
            "t5_summary",
            "gpt2_output"
        ]
    ].head(10)
)

Combined comparison shape: (50, 13)

,benchmark_id,condition,rating,review_clean,bart_summary,t5_summary,gpt2_output
0,1,Depression,2,Really bad. I didn't feel better at all just c...,Really bad. I didn't feel better at all just c...,"I didn't feel better at all just constantly ""w...",I was diagnosed with a rare form of cancer. I ...
1,2,Anxiety,10,I have have drug related issues for ~15 years....,"After 15 years, 3 months, no drugs, I have fou...","my ""Psychiatrist"" diagnosed me with the word ""...",I was diagnosed with Schizophrenia at the age ...
2,3,Anxiety,10,This medicine saved my life when I was 17 year...,This medicine saved my life when I was 17 year...,this medicine saved my life when I was 17 year...,This is the most common adverse event that occ...
3,4,Anxiety,10,I am 47 with such an exhausting history of anx...,I am 47 with such an exhausting history of anx...,47-year-old is alcohol free with no panic atta...,I was diagnosed with anxiety in the early 1990...
4,5,Depression,9,"Since 2007, I've taken Lexapro in varying dose...","Since 2007, I've taken Lexapro in varying dose...",my body is extremely sensitive to certain type...,I have been taking this for over 2 weeks now. ...
5,6,Anxiety,1,I have used Xanax for the past 15 years for se...,I have used Xanax for the past 15 years for se...,I have used Xanax for the past 15 years for se...,1. Xanax does not work for me.\n\n2. It does n...
6,7,Anxiety,10,Xanax has been a life saver. I have always had...,Xanax has been a life saver. I have always had...,Xanax was diagnosed with a brain tumor at 26. ...,I was diagnosed with a brain tumour at 26 year...
7,8,Anxiety,4,Been on and off anti depressants for 10 years ...,Been on and off anti depressants for 10 years ...,running helps me more than anything but I fear...,I've been taking Paxil for about a year now. I...
8,9,Anxiety,1,I tried it for anxiety and aggresive behavior....,I tried it for anxiety and aggresive behavior....,in a few minutes of taking the first dose I be...,I have been using Buspar for over a year now. ...
9,10,Depression,4,I have been on Cymbalta for depression for 3 w...,I have been on Cymbalta for depression for 3 w...,I have had a wide range of side effects sleepl...,This is a very serious adverse event. I am not...

### Creating the quantitative comparison table

In [26]:
def normalize_text(text):
    """Normalize text before checking whether output copied the source."""
    return " ".join(str(text).lower().split())


def similarity_score(source, output):
    """Calculate text similarity from 0 to 1."""
    return SequenceMatcher(
        None,
        normalize_text(source),
        normalize_text(output)
    ).ratio()


model_settings = {
    "BART": {
        "output_column": "bart_summary",
        "time_column": "bart_inference_seconds",
        "ratio_column": "bart_compression_ratio"
    },
    "T5": {
        "output_column": "t5_summary",
        "time_column": "t5_inference_seconds",
        "ratio_column": "t5_compression_ratio"
    },
    "GPT-2": {
        "output_column": "gpt2_output",
        "time_column": "gpt2_inference_seconds",
        "ratio_column": "gpt2_compression_ratio"
    }
}

benchmark_metrics = []

for model_name, columns in model_settings.items():
    output_column = columns["output_column"]
    time_column = columns["time_column"]
    ratio_column = columns["ratio_column"]

    similarities = comparison_df.apply(
        lambda row: similarity_score(
            row["review_clean"],
            row[output_column]
        ),
        axis=1
    )

    exact_copy_rate = (
        comparison_df.apply(
            lambda row: (
                normalize_text(row["review_clean"])
                == normalize_text(row[output_column])
            ),
            axis=1
        ).mean()
    )

    near_copy_rate = (similarities >= 0.90).mean()

    benchmark_metrics.append(
        {
            "model": model_name,
            "reviews_processed": len(comparison_df),
            "total_inference_seconds": comparison_df[
                time_column
            ].sum(),
            "average_seconds_per_review": comparison_df[
                time_column
            ].mean(),
            "median_seconds_per_review": comparison_df[
                time_column
            ].median(),
            "average_output_source_ratio": comparison_df[
                ratio_column
            ].mean(),
            "exact_copy_rate": exact_copy_rate,
            "near_copy_rate": near_copy_rate
        }
    )

metrics_df = pd.DataFrame(benchmark_metrics)

# Round values for easier reporting
numeric_columns = metrics_df.select_dtypes(
    include="number"
).columns

metrics_df[numeric_columns] = (
    metrics_df[numeric_columns].round(3)
)

metrics_df.to_csv(
    "benchmark_metrics_summary.csv",
    index=False
)

display(metrics_df)

,model,reviews_processed,total_inference_seconds,average_seconds_per_review,median_seconds_per_review,average_output_source_ratio,exact_copy_rate,near_copy_rate
0,BART,50,43.496,0.870,0.851,0.556,0.14,0.20
1,T5,50,37.695,0.754,0.583,0.348,0.02,0.04
2,GPT-2,50,53.174,1.063,0.808,0.814,0.00,0.00

### Creating a Manual Evaluation Template

In [27]:
# Select five Depression and five Anxiety reviews
manual_sample = pd.concat(
    [
        comparison_df[
            comparison_df["condition"] == "Depression"
        ].sample(n=5, random_state=42),

        comparison_df[
            comparison_df["condition"] == "Anxiety"
        ].sample(n=5, random_state=42)
    ],
    ignore_index=True
)

manual_evaluation_rows = []

model_output_columns = {
    "BART": "bart_summary",
    "T5": "t5_summary",
    "GPT-2": "gpt2_output"
}

for _, row in manual_sample.iterrows():
    for model_name, output_column in model_output_columns.items():
        manual_evaluation_rows.append(
            {
                "benchmark_id": row["benchmark_id"],
                "condition": row["condition"],
                "rating": row["rating"],
                "model": model_name,
                "original_review": row["review_clean"],
                "model_output": row[output_column],
                "coherence_1_to_5": "",
                "factual_grounding_1_to_5": "",
                "adverse_event_focus_1_to_5": "",
                "overall_quality_1_to_5": "",
                "notes": ""
            }
        )

manual_evaluation_df = pd.DataFrame(
    manual_evaluation_rows
)

manual_evaluation_df.to_csv(
    "manual_evaluation_template.csv",
    index=False
)

print(
    "Manual evaluation rows:",
    len(manual_evaluation_df)
)

display(manual_evaluation_df.head(9))

Manual evaluation rows: 30

,benchmark_id,condition,rating,model,original_review,model_output,coherence_1_to_5,factual_grounding_1_to_5,adverse_event_focus_1_to_5,overall_quality_1_to_5,notes
0,20,Depression,6,BART,I've been taking Setraline for about two weeks...,I've been taking Setraline for about two weeks...,,,,,
1,20,Depression,6,T5,I've been taking Setraline for about two weeks...,I used to take Paroxetine for 3 years and had ...,,,,,
2,20,Depression,6,GPT-2,I've been taking Setraline for about two weeks...,I have been taking this medication for about 2...,,,,,
3,35,Depression,8,BART,I had no problem with Nortriptyline. I had to ...,I had no problem with Nortriptyline. My proble...,,,,,
4,35,Depression,8,T5,I had no problem with Nortriptyline. I had to ...,nortriptyline took it in conjunction with Lith...,,,,,
5,35,Depression,8,GPT-2,I had no problem with Nortriptyline. I had to ...,I was diagnosed with bipolar disorder in the e...,,,,,
6,1,Depression,2,BART,Really bad. I didn't feel better at all just c...,Really bad. I didn't feel better at all just c...,,,,,
7,1,Depression,2,T5,Really bad. I didn't feel better at all just c...,"I didn't feel better at all just constantly ""w...",,,,,
8,1,Depression,2,GPT-2,Really bad. I didn't feel better at all just c...,I was diagnosed with a rare form of cancer. I ...,,,,,

### ZIP AND DOWNLOAD BENCHMARK FILES

In [28]:
import zipfile
from google.colab import files

files_to_zip = [
    "benchmark_sample_50.csv",
    "bart_results_50.csv",
    "t5_results_50.csv",
    "gpt2_results_50.csv",
    "model_comparison_50.csv",
    "benchmark_metrics_summary.csv",
    "manual_evaluation_template.csv"
]

with zipfile.ZipFile(
    "benchmark_deliverables.zip",
    "w",
    zipfile.ZIP_DEFLATED
) as zip_file:

    for filename in files_to_zip:
        zip_file.write(filename)

print("Created benchmark_deliverables.zip")

files.download("benchmark_deliverables.zip")

Created benchmark_deliverables.zip

### CREATE MANUAL QUALITATIVE EVALUATION TEMPLATE

In [29]:
import pandas as pd

# Select a reproducible balanced sample:
# 5 Depression reviews and 5 Anxiety reviews
depression_sample = comparison_df[
    comparison_df["condition"].str.lower() == "depression"
].sample(
    n=5,
    random_state=42
)

anxiety_sample = comparison_df[
    comparison_df["condition"].str.lower() == "anxiety"
].sample(
    n=5,
    random_state=42
)

manual_sample = pd.concat(
    [depression_sample, anxiety_sample],
    ignore_index=True
).sort_values(
    "benchmark_id"
).reset_index(drop=True)

# Map each model to its output column
model_output_columns = {
    "BART": "bart_summary",
    "T5": "t5_summary",
    "GPT-2": "gpt2_output"
}

evaluation_rows = []

# Create one evaluation row per model for each review
for _, row in manual_sample.iterrows():

    for model_name, output_column in model_output_columns.items():

        evaluation_rows.append(
            {
                "benchmark_id": row["benchmark_id"],
                "condition": row["condition"],
                "rating": row["rating"],
                "model": model_name,
                "original_review": row["review_clean"],
                "model_output": row[output_column],

                # Fill these manually using scores from 1 to 5
                "coherence_1_to_5": "",
                "factual_grounding_1_to_5": "",
                "adverse_event_focus_1_to_5": "",
                "overall_quality_1_to_5": "",

                # Note hallucinations, copying, missing details, etc.
                "notes": ""
            }
        )

manual_evaluation_df = pd.DataFrame(evaluation_rows)

# Save the evaluation sheet
manual_evaluation_df.to_csv(
    "manual_evaluation_template.csv",
    index=False
)

print("Reviews selected:", manual_sample["benchmark_id"].tolist())
print("Number of reviews:", len(manual_sample))
print("Number of evaluation rows:", len(manual_evaluation_df))

display(manual_evaluation_df.head(9))

Reviews selected: [1, 2, 17, 20, 23, 24, 31, 35, 46, 49]
Number of reviews: 10
Number of evaluation rows: 30

,benchmark_id,condition,rating,model,original_review,model_output,coherence_1_to_5,factual_grounding_1_to_5,adverse_event_focus_1_to_5,overall_quality_1_to_5,notes
0,1,Depression,2,BART,Really bad. I didn't feel better at all just c...,Really bad. I didn't feel better at all just c...,,,,,
1,1,Depression,2,T5,Really bad. I didn't feel better at all just c...,"I didn't feel better at all just constantly ""w...",,,,,
2,1,Depression,2,GPT-2,Really bad. I didn't feel better at all just c...,I was diagnosed with a rare form of cancer. I ...,,,,,
3,2,Anxiety,10,BART,I have have drug related issues for ~15 years....,"After 15 years, 3 months, no drugs, I have fou...",,,,,
4,2,Anxiety,10,T5,I have have drug related issues for ~15 years....,"my ""Psychiatrist"" diagnosed me with the word ""...",,,,,
5,2,Anxiety,10,GPT-2,I have have drug related issues for ~15 years....,I was diagnosed with Schizophrenia at the age ...,,,,,
6,17,Anxiety,10,BART,Klonopin is a wonderful drug for anxiety and p...,Klonopin is a wonderful drug for anxiety and p...,,,,,
7,17,Anxiety,10,T5,Klonopin is a wonderful drug for anxiety and p...,Klonopin is a great drug for anxiety and panic...,,,,,
8,17,Anxiety,10,GPT-2,Klonopin is a wonderful drug for anxiety and p...,This is a very good drug for treating anxiety....,,,,,

In [30]:
from google.colab import files

files.download("manual_evaluation_template.csv")

* BART copies a short review accurately: grounding may be 5, but overall quality may be 3 because it did not really summarize.

* T5 produces awkward wording but remains mostly accurate: coherence 2–3, grounding 3–4.

* GPT-2 invents cancer, a brain tumor, age, or diagnosis: grounding 1, overall quality 1.

In [31]:
# Display each selected review with all three model outputs
import textwrap

for benchmark_id in manual_sample["benchmark_id"]:

    row = comparison_df[
        comparison_df["benchmark_id"] == benchmark_id
    ].iloc[0]

    print("\n" + "=" * 110)
    print(f"BENCHMARK ID: {benchmark_id}")
    print(f"CONDITION: {row['condition']}")
    print(f"RATING: {row['rating']}")

    print("\nORIGINAL REVIEW:")
    print(textwrap.fill(str(row["review_clean"]), width=110))

    print("\nBART:")
    print(textwrap.fill(str(row["bart_summary"]), width=110))

    print("\nT5:")
    print(textwrap.fill(str(row["t5_summary"]), width=110))

    print("\nGPT-2:")
    print(textwrap.fill(str(row["gpt2_output"]), width=110))

==============================================================================================================
BENCHMARK ID: 1
CONDITION: Depression
RATING: 2

ORIGINAL REVIEW:
Really bad. I didn't feel better at all just constantly "wired" like I had drank 6 cups of coffee. I couldn't
sleep at all.

BART:
Really bad. I didn't feel better at all just constantly "wired" like I had drank 6 cups of coffee. I couldn't
sleep at all.

T5:
I didn't feel better at all just constantly "wired" like I had drank 6 cups of coffee.

GPT-2:
I was diagnosed with a rare form of cancer. I was told that I would have to undergo chemotherapy for the rest
of my life. I had no idea what to expect. I felt like I was going to die. I went to the doctor and said, "I
don't know what to do. I

==============================================================================================================
BENCHMARK ID: 2
CONDITION: Anxiety
RATING: 10

ORIGINAL REVIEW:
I have have drug related issues for ~15 years. Dope, Speed. My, "Psychiatrist" diagnosed me with the word
"schizophrenia", Anti-Phychotics are, VERY DANGEROUS!, they increased my anxiety and stress, MANY MANY, times
over. Finally, after 15 years, 3 months, no drugs, I have found Oxazepam. 5mg. I read, you can take up too
120mg!. atm, I think I need about 10mg a day. I am doubting, whether I have "schizophrenia", at all. I am down
to 1/2 minimum dose, tablet of, DANGEROUS Latuda. So called "treatment", with Anti-Phychotics, is CRIMINAL.

BART:
After 15 years, 3 months, no drugs, I have found Oxazepam 5mg. I am down to 1/2 minimum dose, tablet of,
DANGEROUS Latuda. So called "treatment", with Anti-Phychotics, is CRIMINAL.

T5:
my "Psychiatrist" diagnosed me with the word "schizophrenia" anti-Phychotics are, VERY DANGEROUS!, they
increased my anxiety and stress, times over. after 15 years, 3 months, no drugs, I have found Oxazep

GPT-2:
I was diagnosed with Schizophrenia at the age of 15. I was diagnosed as schizophrenic at the time of my
diagnosis. I had been diagnosed with schizophrenia for over 15 years. I have never been diagnosed as a
schizophrenic. I do not know if I am schizophrenic or not, but I am

==============================================================================================================
BENCHMARK ID: 17
CONDITION: Anxiety
RATING: 10

ORIGINAL REVIEW:
Klonopin is a wonderful drug for anxiety and panic attacks. However, once you start it is very hard to come
off of. I stopped for 2 yrs and it took me 8 months to feel normal again. But if you really need it, this in
my opinion works wonderful for anxiety and panic attacks.

BART:
Klonopin is a wonderful drug for anxiety and panic attacks. Once you start it is very hard to come off of. I
stopped for 2 yrs and it took me 8 months to feel normal again.

T5:
Klonopin is a great drug for anxiety and panic attacks. it took me 8 months to feel normal again.

GPT-2:
This is a very good drug for treating anxiety. It is very effective in treating panic attacks, but it is not
as effective as other drugs. It does not cause any side effects. It can be used in combination with other
drugs to treat panic attacks or to treat anxiety disorders. The side effects of this drug

==============================================================================================================
BENCHMARK ID: 20
CONDITION: Depression
RATING: 6

ORIGINAL REVIEW:
I've been taking Setraline for about two weeks for Social anxiety and depression. . I used to take Paroxetine
for 3 years and had to switch to Sertraline. Since I'm taking Sertraline I've noticed that I am grumpy and
have a very short temper. Any little thing can blow my lid and I honestly hate myself at the moment. I'm so
easily irritated that it really annoys me. Yes, I'm getting mad at myself for getting mad at anything. I
experience no sexual side effects which is good because Paroxetine kind of muted me down there. It doesn't
help much with my depression or social anxiety at the moment. I'll give it a month and maybe increase the
dosage.

BART:
I've been taking Setraline for about two weeks for Social anxiety and depression. I experience no sexual side
effects which is good because Paroxetine kind of muted me down there. I'll give it a month and maybe increase
the dosage.

T5:
I used to take Paroxetine for 3 years and had to switch to Sertraline. since I'm taking Setraline I've noticed
that I am grumpy and have a very short temper.

GPT-2:
I have been taking this medication for about 2 weeks now. I've been using it for about a month now and I've
had no negative side effects. I feel like I'm on the right track. I don't know if I'll be able to get back on
the medication any time soon, but I

==============================================================================================================
BENCHMARK ID: 23
CONDITION: Depression
RATING: 1

ORIGINAL REVIEW:
This medicine has done nothing for my anxiety and depression, but it has made me impotent, fat, lethargic, and
I am suffering from angioedema regularly. (Look that one up, and enjoy)

BART:
This medicine has done nothing for my anxiety and depression, but it has made me impotent, fat, lethargic, and
I am suffering from angioedema regularly.

T5:
this medicine has made me impotent, fat, lethargic, and I am suffering from angioedema.

GPT-2:
This is a very good medicine, but I am not sure if it will work for me or not.  I have been using this
medicine for over a year now, and it has been very effective. I am very happy with the results. I would
recommend this medicine to anyone who is suffering from anxiety

==============================================================================================================
BENCHMARK ID: 24
CONDITION: Anxiety
RATING: 10

ORIGINAL REVIEW:
I have been on Clonezepam for 2 different reasons. 1 for Anxiety 1mg pill 3xs a day, and then 1mg at bedtime
to help Insomnia. It REALLY helps with the anxiety part with me losing both parents & dealing with my own
rheumatoid arthritis at age 26. To those worried about becoming addicted or physically dependent on this
medicine, I wouldn't worry about it too much as I been on it for 3 yrs now and I haven't had to had to up my
dose at all and have been on steady 4mg daily. There were a few times where my doctor went on vacation & it
was my fault for not getting my script early. My Anxiety was bad for 3-4 days BUT I felt NO WITHDRAWALS or
SICKNESS at all from lack of the clonazepam.

BART:
I have been on Clonezepam for 2 different reasons. 1 for Anxiety 1mg pill 3xs a day, and then 1mg at bedtime
to help Insomnia. It REALLY helps with the anxiety part with me losing both parents & dealing with my own
rheumatoid arthritis at age 26

T5:
I have been on Clonezepam for 2 different reasons. 1 for Anxiety 1mg pill 3xs a day, and then 1 mg at bedtime
to help Insomnia.

GPT-2:
I was on a 2-week trial of Clonezapam for the first time in my life. I had been taking it for about 2 weeks
and I had no symptoms at all. I went to the doctor and told him that I was going to take it for 2 weeks. He
told me that I

==============================================================================================================
BENCHMARK ID: 31
CONDITION: Anxiety
RATING: 1

ORIGINAL REVIEW:
BEWARE!! Some people have no problem with this benzodiazepine yet there are many who do such as myself. I took
it for hyper thyroid. It has ruined the last 14 months of my life!!! Words cannot express the mental and
physical torture I experience daily. PLEASE Google Professor Ashton to read the side effects. Visit Benzo
Buddies. You will learn about the horrors these meds cause as well as success stories of those who survived
this! There has been a bill introduced in Massachusetts to get doctors to warn their patients!! Warn everyone
you know! Don't be fooled! My world has been turned upside down and I don't want it to happen to you!!

BART:
BEWARE!! Some people have no problem with this benzodiazepine yet there are many who do such as myself. It has
ruined the last 14 months of my life!!! Words cannot express the mental and physical torture I experience
daily. Please Google Professor Ashton to read the side effects. Visit Benzo

T5:
benzodiazepine has ruined the last 14 months of my life. there has been a bill introduced in Massachusetts to
get doctors to warn their patients.

GPT-2:
I have been taking this medication for over a year now. I have never experienced anything like this before. I
am very happy with the results. I will continue to take this medication as long as I can. I do not know how
long it will last, but I am sure it will be worth it.

==============================================================================================================
BENCHMARK ID: 35
CONDITION: Depression
RATING: 8

ORIGINAL REVIEW:
I had no problem with Nortriptyline. I had to take it in conjunction with Lithium for depression. My problem
was when I QUIT taking it. I'm dizzy, sick to my stomach, I have ringing in my ears, I'm irritated all the
time and I can't sleep. Just be prepared in case you stop taking it too.

BART:
I had no problem with Nortriptyline. My problem was when I QUIT taking it. I'm dizzy, sick to my stomach, I
have ringing in my ears, I'm irritated all the time and I can't sleep. Just be prepared in case you stop
taking it too.

T5:
nortriptyline took it in conjunction with Lithium for depression. I'm dizzy, sick to my stomach, I have
ringing in my ears.

GPT-2:
I was diagnosed with bipolar disorder in the early 1990s. I was diagnosed as having bipolar disorder at the
time of my diagnosis. I have been diagnosed with depression since I was 12 years old. I am currently on a
medication to treat my bipolar disorder. I do not know if I will ever be able to

==============================================================================================================
BENCHMARK ID: 46
CONDITION: Depression
RATING: 10

ORIGINAL REVIEW:
My dr gave me two sample packs and told me to take all the 10mg tablets and once I was done I could go up to
20mg if I needed it, but I continue to get a prescription for 20mg and cut them in half so it lasts me twice
as long. She told me I would have upset stomach the first night and that was literally the only bad side
effect I had! I take it after dinner/before bed. Right away it made me feel more awake, able to handle things
my stressors better, and gave me a general sense of well being. I can still get aggravated so I don't feel
like a zombie, and I'm still able to have the big O. I am 36 and have tried 10 or so different antidepressants
over the years since I was in my late teens and nothing has ever worked as well as this.

BART:
My dr gave me two sample packs and told me to take all the 10mg tablets and once I was done I could go up to
20mg if I needed it. She told me I would have upset stomach the first night and that was literally the only
bad side effect I had! I take it after

T5:
dr gave me two sample packs and told me to take all the 10mg tablets. she told me I would have upset stomach
the first night. right away it made me feel more awake, able to handle things my stressors better, and gave me
a general sense of well

GPT-2:
I have been taking this medication for over a year now and I have never had an adverse event. I have had a few
side effects, but none of them have affected me at all. The only thing that has changed is that I have been
able to sleep better and I am able to eat better. I

==============================================================================================================
BENCHMARK ID: 49
CONDITION: Anxiety
RATING: 8

ORIGINAL REVIEW:
There are a lot of negative reviews about this medicine and it's side effects, and that makes a lot of people
beginning the medicine, including myself, freak out. The people having a positive experience with Lexapro are
out living life. Don't be discouraged. For me, Lexapro started working in the second week, but would work on
and off for the first month. I started at 5mg and slowly went up to 15. I'm on week 5 and it hasn't done much
for my anxiety (yet) but it has helped my moods tremendously. For the first month I had muscle aches and
headaches, and I was really tired and unmotivated. That went away in week 4 and I'm feeling better than I have
felt in two years.

BART:
There are a lot of negative reviews about this medicine and it's side effects. Don't be discouraged. The
people having a positive experience with Lexapro are out living life.

T5:
the people having a positive experience with Lexapro are out living life. I started at 5mg and slowly went up
to 15. for the first month I had muscle aches and headaches.

GPT-2:
Lexapro has been approved by the FDA for use in the treatment of anxiety and depression. It has been shown to
be safe and effective in treating a wide range of conditions, including anxiety, depression, bipolar disorder,
anxiety disorders, and post-traumatic stress disorder (PTSD).  It is

### Uploading the manual_evaluation_completed.csv

In [41]:
from google.colab import files
import pandas as pd

# Upload manual_evaluation_completed.csv
uploaded = files.upload()

# Get the exact filename assigned by Colab
uploaded_filename = next(iter(uploaded))

print("Uploaded filename:", uploaded_filename)

# Load the completed evaluation
manual_evaluation_df = pd.read_csv(uploaded_filename)

print("Rows loaded:", len(manual_evaluation_df))
display(manual_evaluation_df.head())

Saving manual_evaluation_completed.csv to manual_evaluation_completed.csv
Uploaded filename: manual_evaluation_completed.csv
Rows loaded: 30

,benchmark_id,condition,rating,model,original_review,model_output,coherence_1_to_5,factual_grounding_1_to_5,adverse_event_focus_1_to_5,overall_quality_1_to_5,notes
0,1,Depression,2,BART,Really bad. I didn't feel better at all just c...,Really bad. I didn't feel better at all just c...,5,5,5,4,"Accurate and coherent, but essentially copies ..."
1,1,Depression,2,T5,Really bad. I didn't feel better at all just c...,"I didn't feel better at all just constantly ""w...",4,5,3,3,"Grounded and concise, but omits the reported i..."
2,1,Depression,2,GPT-2,Really bad. I didn't feel better at all just c...,I was diagnosed with a rare form of cancer. I ...,3,1,1,1,"Hallucinates cancer, chemotherapy, and other u..."
3,2,Anxiety,10,BART,I have have drug related issues for ~15 years....,"After 15 years, 3 months, no drugs, I have fou...",4,5,2,2,Grounded but preserves inflammatory wording an...
4,2,Anxiety,10,T5,I have have drug related issues for ~15 years....,"my ""Psychiatrist"" diagnosed me with the word ""...",2,4,4,2,"Captures increased anxiety and stress, but the..."

### Calculating the Scores

In [42]:
score_columns = [
    "coherence_1_to_5",
    "factual_grounding_1_to_5",
    "adverse_event_focus_1_to_5",
    "overall_quality_1_to_5"
]

qualitative_summary_df = (
    manual_evaluation_df
    .groupby("model")[score_columns]
    .mean()
    .round(2)
    .reset_index()
)

display(qualitative_summary_df)

,model,coherence_1_to_5,factual_grounding_1_to_5,adverse_event_focus_1_to_5,overall_quality_1_to_5
0,BART,4.5,5.0,3.3,3.4
1,GPT-2,3.4,1.0,1.0,1.0
2,T5,3.5,4.9,3.6,3.1